### ISSUE TITLE
LookupPayloadInjectingProxyThread 的修改建议

### ISSUE THREAD

**Issue by G0doot** [lalajun/RMIDeserialize#3]
LookupPayloadInjectingProxyThread的handleData中用于捕获替换RMI请求的if判断：
`if(dataBytes.length > 7 && dataBytes[0] == (byte)0x50) {`
在一些网络环境下会失效，测试发现ecs上跑的时候会出现这个问题。

原因在于tcp的粘包，有时候这个0x50开头的包会和前面发送的那个包含ip地址的rmi包粘在一起，导致该if判断失效，建议改成：
```
int indexOf = indexOfByteArray(dataBytes, new byte[]{(byte)0x50, (byte)0xac, (byte)0xed});
    if(dataBytes.length > 7 && indexOf != -1) {
    //blockLen和out.write偏移位也需要改一下，加上indexof
```

**Comment by lalajun** [comment]
非常感谢反馈，这边已经修改了代码，由于本机没有你说的这种环境，也只是在本机环境测试成功啦。
不过你说的这个问题真是没遇到过，非常的神奇，如果还有什么问题可以反馈我噢。

**Comment by G0doot** [comment]
感谢修改🙏。我遇到这个问题也挺惊讶的，粘包一般出现在跨主机的场景下，没想到这个本地端口间的Proxy也出现了这个问题，如图所示，这个50开头的正常情况应该是和上面那一行分开，但是现在粘在一起了，就没有进入到if。
![image](https://user-images.githubusercontent.com/23240796/91786290-de97c200-ec39-11ea-8951-5ea62abb22e6.png)
当时debug找了好久😂，看来socket通信还是得时刻注意粘包的问题。
